# Tabloza MidiExpander — rtpmidid config
# Mac/Windows vedono il dispositivo come sessione RTP-MIDI su porta 5004

[general]
alsa_name=rtpmidid
control=/var/run/rtpmidid/control.sock

[rtpmidi_announce]
name=tabloza-me
port=5004

[alsa_announce]
name=Network Export
